feat : lenet (#75)
We've finally found something worse than my cooking: dace has a bug!!!


```
/usr/bin/python3 /home/jfreeman/npbench/run_benchmark.py -p paper -f triton -b lenet 
***** Testing Triton with lenet on the paper dataset, datatype default *****
NumPy - default - validation: 2265ms
Triton - default - first/validation: 60214ms
Triton - default - default - validation: SUCCESS
Triton - default - median: 127ms
```

DACE:
```
/usr/bin/python3 /home/jfreeman/npbench/run_benchmark.py -p paper -f dace_gpu -b lenet 
/usr/local/lib/python3.12/dist-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
***** Testing DaCe GPU with lenet on the paper dataset, datatype default *****
NumPy - default - validation: 2283ms
Failing SDFG saved for inspection in /home/jfreeman/npbench/_dacegraphs/failing.sdfgz
Failed to compile DaCe gpu fusion implementation.
Ambiguous or invalid edge to/from a View access node (at state block, node _in)
Originating from source code at File "/usr/local/lib/python3.12/dist-packages/dace/libraries/standard/nodes/reduce.py", line 1466
Invalid SDFG saved for inspection in /home/jfreeman/npbench/_dacegraphs/invalid.sdfgz
Traceback (most recent call last):
  File "/home/jfreeman/npbench/npbench/infrastructure/dace_framework.py", line 277, in implementations
    dc_exec, compile_time = util.benchmark("__npb_result = sdfg.compile()",
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jfreeman/npbench/npbench/infrastructure/utilities.py", line 138, in benchmark
    raw_time_list = timeit.repeat(stmt, setup=setup, repeat=repeat, number=1, globals=ldict)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 243, in repeat
    return Timer(stmt, setup, timer, globals).repeat(repeat, number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 208, in repeat
    t = self.timeit(number)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 180, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 6, in inner
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/sdfg.py", line 2358, in compile
    program_objects = codegen.generate_code(sdfg, validate=validate)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/dace/codegen/codegen.py", line 195, in generate_code
    sdfg.expand_library_nodes()
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/sdfg.py", line 2796, in expand_library_nodes
    impl_name = node.expand(self, state)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/nodes.py", line 1415, in expand
    transformation.apply(state, sdfg, *args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/dace/transformation/transformation.py", line 707, in apply
    expansion = type(self).expansion(node, state, sdfg, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/dace/libraries/standard/nodes/reduce.py", line 1535, in expansion
    nsdfg.apply_transformations_repeated(dataflow.MapCollapse)
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/sdfg.py", line 2676, in apply_transformations_repeated
    results = pazz.apply_pass(self, {})
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/dace/transformation/passes/pattern_matching.py", line 285, in apply_pass
    return self._apply_pass(sdfg, pipeline_results, apply_once=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/dace/transformation/passes/pattern_matching.py", line 273, in _apply_pass
    raise err
  File "/usr/local/lib/python3.12/dist-packages/dace/transformation/passes/pattern_matching.py", line 267, in _apply_pass
    sdfg.validate()
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/sdfg.py", line 2474, in validate
    validate_sdfg(self, references, **context)
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/validation.py", line 315, in validate_sdfg
    validate_control_flow_region(sdfg, sdfg, initialized_transients, symbols, references, **context)
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/validation.py", line 148, in validate_control_flow_region
    validate_state(start_block, region.node_id(start_block), sdfg, symbols, initialized_transients, references,
  File "/usr/local/lib/python3.12/dist-packages/dace/sdfg/validation.py", line 503, in validate_state
    raise InvalidSDFGNodeError("Ambiguous or invalid edge to/from a View access node", sdfg, state_id,
dace.sdfg.validation.InvalidSDFGNodeError: Ambiguous or invalid edge to/from a View access node (at state block, node _in)
Originating from source code at File "/usr/local/lib/python3.12/dist-packages/dace/libraries/standard/nodes/reduce.py", line 1466
Invalid SDFG saved for inspection in /home/jfreeman/npbench/_dacegraphs/invalid.sdfgz
Traceback
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuBLAS failed with error code: 1

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)

```