Fix markupsafe version to fix Jax (#97)
When running Jax with `uv`, we get the following errors:

```
$ uv run run_benchmark.py -p paper -f jax -b jacobi_1d
/home/rwohlbold/npbench/npbench/infrastructure/framework.py:5: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
***** Testing Jax with jacobi_1d on the paper dataset, datatype default *****
NumPy - default - validation: 122ms
W1216 12:47:55.907518   31282 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.
W1216 12:47:55.915045   31200 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.
E1216 12:47:55.960788   31200 cuda_dnn.cc:456] Loaded runtime CuDNN library: 9.10.2 but source was compiled with: 9.12.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
E1216 12:47:55.966134   31200 cuda_dnn.cc:456] Loaded runtime CuDNN library: 9.10.2 but source was compiled with: 9.12.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
E1216 12:47:56.052752   31200 cuda_dnn.cc:456] Loaded runtime CuDNN library: 9.10.2 but source was compiled with: 9.12.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
E1216 12:47:56.059152   31200 cuda_dnn.cc:456] Loaded runtime CuDNN library: 9.10.2 but source was compiled with: 9.12.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Failed to execute the Jax - default implementation.
Traceback (most recent call last):
  File "/home/rwohlbold/npbench/npbench/infrastructure/test.py", line 33, in _execute
    out, timelist = util.benchmark(exec_str, setup_str, report_str + " - " + mode, repeat, ldict,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/npbench/infrastructure/utilities.py", line 138, in benchmark
    raw_time_list = timeit.repeat(stmt, setup=setup, repeat=repeat, number=1, globals=ldict)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 243, in repeat
    return Timer(stmt, setup, timer, globals).repeat(repeat, number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 208, in repeat
    t = self.timeit(number)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 180, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 3, in inner
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/numpy/array_constructors.py", line 286, in array
    out_array: Array = lax._convert_element_type(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/lax/lax.py", line 1727, in _convert_element_type
    return convert_element_type_p.bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 632, in bind
    return self._true_bind(*args, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 648, in _true_bind
    return self.bind_with_trace(prev_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/lax/lax.py", line 5035, in _convert_element_type_bind_with_trace
    operand = core.Primitive.bind_with_trace(convert_element_type_p, trace, args, params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 660, in bind_with_trace
    return trace.process_primitive(self, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 1189, in process_primitive
    return primitive.impl(*args, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/dispatch.py", line 92, in apply_primitive
    outs = fun(*args)
           ^^^^^^^^^^
jax.errors.JaxRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
Jax - default did not return enough elements. Maybe you forgot a return statement?
Failed to run Jax validation.
Traceback (most recent call last):
  File "/home/rwohlbold/npbench/npbench/infrastructure/test.py", line 140, in run
    valid = util.validate(np_out, frmwrk_out, frmwrk_name, rtol=rtol, atol=atol, norm_error=norm_error)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/npbench/infrastructure/utilities.py", line 168, in validate
    if not np.allclose(r, v, rtol=rtol, atol=atol):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/numpy/_core/numeric.py", line 2365, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/numpy/_core/numeric.py", line 2496, in isclose
    result = (less_equal(abs(x - y), atol + rtol * abs(y))
                             ~~^~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
E1216 12:47:56.077298   31200 cuda_dnn.cc:456] Loaded runtime CuDNN library: 9.10.2 but source was compiled with: 9.12.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
E1216 12:47:56.083139   31200 cuda_dnn.cc:456] Loaded runtime CuDNN library: 9.10.2 but source was compiled with: 9.12.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Failed to execute the Jax - default implementation.
Traceback (most recent call last):
  File "/home/rwohlbold/npbench/npbench/infrastructure/test.py", line 33, in _execute
    out, timelist = util.benchmark(exec_str, setup_str, report_str + " - " + mode, repeat, ldict,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/npbench/infrastructure/utilities.py", line 138, in benchmark
    raw_time_list = timeit.repeat(stmt, setup=setup, repeat=repeat, number=1, globals=ldict)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 243, in repeat
    return Timer(stmt, setup, timer, globals).repeat(repeat, number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 208, in repeat
    t = self.timeit(number)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/timeit.py", line 180, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 3, in inner
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/numpy/array_constructors.py", line 286, in array
    out_array: Array = lax._convert_element_type(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/lax/lax.py", line 1727, in _convert_element_type
    return convert_element_type_p.bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 632, in bind
    return self._true_bind(*args, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 648, in _true_bind
    return self.bind_with_trace(prev_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/lax/lax.py", line 5035, in _convert_element_type_bind_with_trace
    operand = core.Primitive.bind_with_trace(convert_element_type_p, trace, args, params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 660, in bind_with_trace
    return trace.process_primitive(self, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/core.py", line 1189, in process_primitive
    return primitive.impl(*args, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwohlbold/npbench/.venv/lib/python3.12/site-packages/jax/_src/dispatch.py", line 92, in apply_primitive
    outs = fun(*args)
           ^^^^^^^^^^
jax.errors.JaxRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

Adding the following to `pyproject.toml` is supposed to improve this
issue:

```toml
[tool.uv.sources]
torch = { index = "pytorch-cu130" }

[[tool.uv.index]]
explicit = true
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
```

However, we got the following error:

```
error: Distribution `markupsafe==3.0.2 @ registry+https://download.pytorch.org/whl/cu130` can't be installed because it doesn't have a source distribution or wheel for the current platform

hint: You're using CPython 3.12 (`cp312`), but `markupsafe` (v3.0.2) only has wheels with the following Python implementation tag: `cp313`
```

We solve this by fixing `markupsafe` to version `2.1.3`. This has Jax
run without issues:

```sh
$ uv run run_benchmark.py -p paper -f jax -b jacobi_1d
Installed 78 packages in 933ms
***** Testing Jax with jacobi_1d on the paper dataset, datatype default *****
NumPy - default - validation: 122ms
W1216 13:04:35.823189   51896 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.
W1216 13:04:35.826478   51798 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.
Jax - default - first/validation: 153ms
Jax - default - default - validation: SUCCESS
Jax - default - median: 69ms
```